[package]
name = "jeth-inlines-blake2f"
version.workspace = true
edition.workspace = true

[features]
default = []
host = ["jolt-inlines-sdk/host"]

[dependencies]
jolt-inlines-sdk = { git = "https://github.com/a16z/jolt", rev = "8e536f199735ac8187156aa589ed1387722a079a", default-features = false }

[dev-dependencies]
jeth-inlines-blake2f = { path = ".", features = ["host"] }
jolt-inlines-sdk = { git = "https://github.com/a16z/jolt", rev = "8e536f199735ac8187156aa589ed1387722a079a", default-features = false, features = ["test-utils"] }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
tracer = { git = "https://github.com/a16z/jolt", rev = "8e536f199735ac8187156aa589ed1387722a079a", features = ["std", "test-utils"] }

[lints]
workspace = true
